Fix own cmake files - also create symlink from INCLUDE cmake
RadeonOpenCompute/rocm-cmake pull request #107
Opened 2022-08-04 23:22 UTC by yhmtsai

from 5.2.0, hip and rocm will also add cmake file into `<ROCM>/<PACKAGE>/lib/cmake` (not just `<ROCM>/lib/cmake/<PACAKGE>`)
hiprand and rocrand reports `include could not find load file: ...`
The workaround is link the missing file from `<ROCM>/lib/cmake/<PACAKGE>` to `<ROCM>/<PACKAGE>/lib/cmake`  or use `-D<pacakge_lower_case>_DIR=<ROCM>/<PACKAGE>/lib/cmake` in CMake

Issue:
When cmake find the file inside `<ROCM>/<PACKAGE>/lib/cmake`, it will create issue about cmakefile non-found.
https://github.com/RadeonOpenCompute/rocm-cmake/blob/03ec8374afec9d96afb9cc817fb9258feb84ed32/share/rocm/cmake/ROCMInstallTargets.cmake#L289-L293
only adds the INCLUDE cmake into CONFIG_PACKAGE_INSTALL_DIR, which is `lib/cmake/<PACKAGE>`
and looks for the file from current cmake folder. ( `<ROCM>/<PACKAGE>/lib/cmake`)
Thus, it can not find the file because symlink is not created.

also create the symlink for INCLUDE cmakefile.
another way is to change the path to look for the INCLUDE, but I think all cmake should be under the same folder from the rocm cmakefile structure

2022-08-05 16:59 UTC, lawruble13 requested changes
Thank you for pointing out the issue and suggesting a fix!

If we want to go this route to fix the problem, the noted changes should be made.

I'm of the opinion that a better route may be to resolve `CMAKE_CURRENT_LIST_DIR` using `get_filename_component(... REALPATH)` in the configuration file, although I'm not certain and will do some experimenting with the alternatives.

2022-08-05 16:59 UTC, lawruble13 commented on share/rocm/cmake/ROCMInstallTargets.cmake
> +        list(APPEND PARSE_INCLUDE_NAME ${INCLUDE_BASE})
Can you rename the `PARSE_INCLUDE_NAME` variable you're using here, possibly to something like `INCLUDED_FILES`? `PARSE_INCLUDE_NAME` suggests that `INCLUDE_NAME` is an argument to `rocm_export_targets`.

2022-08-05 16:59 UTC, lawruble13 commented on share/rocm/cmake/ROCMInstallTargets.cmake
> +        list(APPEND PARSE_INCLUDE_NAME ${INCLUDE_BASE})
Whatever variable we use should be cleared at the start of the function, to avoid accidentally using values from the calling scope.

2022-08-05 22:25 UTC, yhmtsai commented
@lawruble13 Thanks for suggestion.
Another way might be glob all *.cmake from the source dir.
I am sure whether it will lead the circular issue I posted before again.
Also, sorry for no further reply in posted issue. I missed the notification

2022-08-23 20:03 UTC, lawruble13 approved these changes
This looks good to me, having tested & considered I think that this solution is fine, especially as this segment of code is to support backwards compatibility and will be removed eventually.

2022-11-20 22:34 UTC, cgmb approved these changes
The fix is probably going to end up in ROCm 5.5, so it might only be a single release before it's made irrelevant by the removal of the compatibility layout. Nevertheless... pushing the fix forward by a few months is still nice.

2022-11-20 22:37 UTC, merged