Add codeowners for documentation
RadeonOpenCompute/rocm-cmake pull request #168
Opened 2024-01-24 23:27 UTC by samjwu

Relates to https://github.com/ROCm/ROCm/issues/2832
Adding documentation team as codeowners for documentation.
Goal is to make this group of code owners reviewers when merging documentation changes. The header directory is related to documentation and thus changes to that are also flagged for documentation review.

**Please note that this requires the team to be added as a role with Write permissions.**

2024-02-01 00:28 UTC, cgmb requested changes
Please remove the executable permissions from the codeowners file.

2024-02-01 17:12 UTC, samjwu commented
> Please remove the executable permissions from the codeowners file.

Fixed in latest.

Also, would someone with admin permissions to this repo be able to add the ROCm Documentation team with write permissions? GitHub flags the additions to the CODEOWNER file as an error otherwise. Thanks!

2024-02-01 22:06 UTC, eidenyoshida commented
@samjwu I added the docs team with write privilege

can you also add the original code owners to all the docs files?

2024-02-07 05:16 UTC, cgmb approved these changes

2024-02-07 20:28 UTC, merged